//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for estimatedPaymentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="estimatedPaymentData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estimateTotalCost" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="monthlyPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="simplyPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "estimatedPaymentData", namespace = "http://axes.alldata.net/web-services/sales", propOrder = {
    "estimateTotalCost",
    "monthlyPaymentAmount",
    "simplyPaymentAmount"
})
public class EstimatedPaymentData {

    protected Double estimateTotalCost;
    protected Double monthlyPaymentAmount;
    protected Double simplyPaymentAmount;

    /**
     * Gets the value of the estimateTotalCost property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEstimateTotalCost() {
        return estimateTotalCost;
    }

    /**
     * Sets the value of the estimateTotalCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEstimateTotalCost(Double value) {
        this.estimateTotalCost = value;
    }

    /**
     * Gets the value of the monthlyPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMonthlyPaymentAmount() {
        return monthlyPaymentAmount;
    }

    /**
     * Sets the value of the monthlyPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMonthlyPaymentAmount(Double value) {
        this.monthlyPaymentAmount = value;
    }

    /**
     * Gets the value of the simplyPaymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSimplyPaymentAmount() {
        return simplyPaymentAmount;
    }

    /**
     * Sets the value of the simplyPaymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSimplyPaymentAmount(Double value) {
        this.simplyPaymentAmount = value;
    }

}
