//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.alldata.axes.web_services.sales package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sales30_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales30");
    private final static QName _Sales31_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales31");
    private final static QName _Sales30Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales30Response");
    private final static QName _Sales32_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales32");
    private final static QName _Sales31Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales31Response");
    private final static QName _Sales32Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales32Response");
    private final static QName _Sales33_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales33");
    private final static QName _Sales33Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales33Response");
    private final static QName _Sales34_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales34");
    private final static QName _Sales34Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales34Response");
    private final static QName _Sales35_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales35");
    private final static QName _Sales35Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales35Response");
    private final static QName _Sales36_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales36");
    private final static QName _Sales36Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales36Response");
    private final static QName _Sales37_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales37");
    private final static QName _Sales37Response_QNAME = new QName("http://axes.alldata.net/web-services/sales", "sales37Response");
    private final static QName _Credentials_QNAME = new QName("http://axes.alldata.net/web-services/sales", "credentials");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.alldata.axes.web_services.sales
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sales31Response }
     * 
     */
    public Sales31Response createSales31Response() {
        return new Sales31Response();
    }

    /**
     * Create an instance of {@link Sales34Response }
     * 
     */
    public Sales34Response createSales34Response() {
        return new Sales34Response();
    }

    /**
     * Create an instance of {@link SalesResponse35 }
     * 
     */
    public SalesResponse35 createSalesResponse35() {
        return new SalesResponse35();
    }

    /**
     * Create an instance of {@link SalesRequest33 }
     * 
     */
    public SalesRequest33 createSalesRequest33() {
        return new SalesRequest33();
    }

    /**
     * Create an instance of {@link MerchantDiscountFee }
     * 
     */
    public MerchantDiscountFee createMerchantDiscountFee() {
        return new MerchantDiscountFee();
    }

    /**
     * Create an instance of {@link SalesRequest34 }
     * 
     */
    public SalesRequest34 createSalesRequest34() {
        return new SalesRequest34();
    }

    /**
     * Create an instance of {@link Sales37Response }
     * 
     */
    public Sales37Response createSales37Response() {
        return new Sales37Response();
    }

    /**
     * Create an instance of {@link SalesRequest37 }
     * 
     */
    public SalesRequest37 createSalesRequest37() {
        return new SalesRequest37();
    }

    /**
     * Create an instance of {@link Sales32 }
     * 
     */
    public Sales32 createSales32() {
        return new Sales32();
    }

    /**
     * Create an instance of {@link Sales34 }
     * 
     */
    public Sales34 createSales34() {
        return new Sales34();
    }

    /**
     * Create an instance of {@link SalesResponse32 }
     * 
     */
    public SalesResponse32 createSalesResponse32() {
        return new SalesResponse32();
    }

    /**
     * Create an instance of {@link NextRewards }
     * 
     */
    public NextRewards createNextRewards() {
        return new NextRewards();
    }

    /**
     * Create an instance of {@link SalesRequest35 }
     * 
     */
    public SalesRequest35 createSalesRequest35() {
        return new SalesRequest35();
    }

    /**
     * Create an instance of {@link SalesResponse33 }
     * 
     */
    public SalesResponse33 createSalesResponse33() {
        return new SalesResponse33();
    }

    /**
     * Create an instance of {@link SalesResponse36 }
     * 
     */
    public SalesResponse36 createSalesResponse36() {
        return new SalesResponse36();
    }

    /**
     * Create an instance of {@link SalesResponse30 }
     * 
     */
    public SalesResponse30 createSalesResponse30() {
        return new SalesResponse30();
    }

    /**
     * Create an instance of {@link SalesRequest36 }
     * 
     */
    public SalesRequest36 createSalesRequest36() {
        return new SalesRequest36();
    }

    /**
     * Create an instance of {@link Sales36Response }
     * 
     */
    public Sales36Response createSales36Response() {
        return new Sales36Response();
    }

    /**
     * Create an instance of {@link Sales36 }
     * 
     */
    public Sales36 createSales36() {
        return new Sales36();
    }

    /**
     * Create an instance of {@link CurrentRewards }
     * 
     */
    public CurrentRewards createCurrentRewards() {
        return new CurrentRewards();
    }

    /**
     * Create an instance of {@link SalesRequest30 }
     * 
     */
    public SalesRequest30 createSalesRequest30() {
        return new SalesRequest30();
    }

    /**
     * Create an instance of {@link Sales30Response }
     * 
     */
    public Sales30Response createSales30Response() {
        return new Sales30Response();
    }

    /**
     * Create an instance of {@link Sales33Response }
     * 
     */
    public Sales33Response createSales33Response() {
        return new Sales33Response();
    }

    /**
     * Create an instance of {@link EstimatedPaymentData }
     * 
     */
    public EstimatedPaymentData createEstimatedPaymentData() {
        return new EstimatedPaymentData();
    }

    /**
     * Create an instance of {@link Sales35 }
     * 
     */
    public Sales35 createSales35() {
        return new Sales35();
    }

    /**
     * Create an instance of {@link AvsValidation }
     * 
     */
    public AvsValidation createAvsValidation() {
        return new AvsValidation();
    }

    /**
     * Create an instance of {@link SalesResponse34 }
     * 
     */
    public SalesResponse34 createSalesResponse34() {
        return new SalesResponse34();
    }

    /**
     * Create an instance of {@link SalesRequest31 }
     * 
     */
    public SalesRequest31 createSalesRequest31() {
        return new SalesRequest31();
    }

    /**
     * Create an instance of {@link SalesResponse37 }
     * 
     */
    public SalesResponse37 createSalesResponse37() {
        return new SalesResponse37();
    }

    /**
     * Create an instance of {@link CurrentRewards10 }
     * 
     */
    public CurrentRewards10 createCurrentRewards10() {
        return new CurrentRewards10();
    }

    /**
     * Create an instance of {@link Sales32Response }
     * 
     */
    public Sales32Response createSales32Response() {
        return new Sales32Response();
    }

    /**
     * Create an instance of {@link Credentials }
     * 
     */
    public Credentials createCredentials() {
        return new Credentials();
    }

    /**
     * Create an instance of {@link Sales35Response }
     * 
     */
    public Sales35Response createSales35Response() {
        return new Sales35Response();
    }

    /**
     * Create an instance of {@link Sales30 }
     * 
     */
    public Sales30 createSales30() {
        return new Sales30();
    }

    /**
     * Create an instance of {@link Sales37 }
     * 
     */
    public Sales37 createSales37() {
        return new Sales37();
    }

    /**
     * Create an instance of {@link ClientHeader }
     * 
     */
    public ClientHeader createClientHeader() {
        return new ClientHeader();
    }

    /**
     * Create an instance of {@link Sales31 }
     * 
     */
    public Sales31 createSales31() {
        return new Sales31();
    }

    /**
     * Create an instance of {@link SalesRequest32 }
     * 
     */
    public SalesRequest32 createSalesRequest32() {
        return new SalesRequest32();
    }

    /**
     * Create an instance of {@link SalesResponse31 }
     * 
     */
    public SalesResponse31 createSalesResponse31() {
        return new SalesResponse31();
    }

    /**
     * Create an instance of {@link Sales33 }
     * 
     */
    public Sales33 createSales33() {
        return new Sales33();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales30 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales30")
    public JAXBElement<Sales30> createSales30(Sales30 value) {
        return new JAXBElement<Sales30>(_Sales30_QNAME, Sales30 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales31 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales31")
    public JAXBElement<Sales31> createSales31(Sales31 value) {
        return new JAXBElement<Sales31>(_Sales31_QNAME, Sales31 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales30Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales30Response")
    public JAXBElement<Sales30Response> createSales30Response(Sales30Response value) {
        return new JAXBElement<Sales30Response>(_Sales30Response_QNAME, Sales30Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales32 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales32")
    public JAXBElement<Sales32> createSales32(Sales32 value) {
        return new JAXBElement<Sales32>(_Sales32_QNAME, Sales32 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales31Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales31Response")
    public JAXBElement<Sales31Response> createSales31Response(Sales31Response value) {
        return new JAXBElement<Sales31Response>(_Sales31Response_QNAME, Sales31Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales32Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales32Response")
    public JAXBElement<Sales32Response> createSales32Response(Sales32Response value) {
        return new JAXBElement<Sales32Response>(_Sales32Response_QNAME, Sales32Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales33 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales33")
    public JAXBElement<Sales33> createSales33(Sales33 value) {
        return new JAXBElement<Sales33>(_Sales33_QNAME, Sales33 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales33Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales33Response")
    public JAXBElement<Sales33Response> createSales33Response(Sales33Response value) {
        return new JAXBElement<Sales33Response>(_Sales33Response_QNAME, Sales33Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales34 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales34")
    public JAXBElement<Sales34> createSales34(Sales34 value) {
        return new JAXBElement<Sales34>(_Sales34_QNAME, Sales34 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales34Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales34Response")
    public JAXBElement<Sales34Response> createSales34Response(Sales34Response value) {
        return new JAXBElement<Sales34Response>(_Sales34Response_QNAME, Sales34Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales35 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales35")
    public JAXBElement<Sales35> createSales35(Sales35 value) {
        return new JAXBElement<Sales35>(_Sales35_QNAME, Sales35 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales35Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales35Response")
    public JAXBElement<Sales35Response> createSales35Response(Sales35Response value) {
        return new JAXBElement<Sales35Response>(_Sales35Response_QNAME, Sales35Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales36 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales36")
    public JAXBElement<Sales36> createSales36(Sales36 value) {
        return new JAXBElement<Sales36>(_Sales36_QNAME, Sales36 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales36Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales36Response")
    public JAXBElement<Sales36Response> createSales36Response(Sales36Response value) {
        return new JAXBElement<Sales36Response>(_Sales36Response_QNAME, Sales36Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales37 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales37")
    public JAXBElement<Sales37> createSales37(Sales37 value) {
        return new JAXBElement<Sales37>(_Sales37_QNAME, Sales37 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sales37Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "sales37Response")
    public JAXBElement<Sales37Response> createSales37Response(Sales37Response value) {
        return new JAXBElement<Sales37Response>(_Sales37Response_QNAME, Sales37Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Credentials }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/sales", name = "credentials")
    public JAXBElement<Credentials> createCredentials(Credentials value) {
        return new JAXBElement<Credentials>(_Credentials_QNAME, Credentials.class, null, value);
    }

}
