//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salesRequest34 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesRequest34">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/sales}salesRequest33">
 *       &lt;sequence>
 *         &lt;element name="cardHolderPresentInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardPresentInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salesRequest34", namespace = "http://axes.alldata.net/web-services/sales", propOrder = {
    "cardHolderPresentInd",
    "cardPresentInd"
})
@XmlSeeAlso({
    SalesRequest35 .class
})
public class SalesRequest34
    extends SalesRequest33
{

    protected String cardHolderPresentInd;
    protected String cardPresentInd;

    /**
     * Gets the value of the cardHolderPresentInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolderPresentInd() {
        return cardHolderPresentInd;
    }

    /**
     * Sets the value of the cardHolderPresentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolderPresentInd(String value) {
        this.cardHolderPresentInd = value;
    }

    /**
     * Gets the value of the cardPresentInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardPresentInd() {
        return cardPresentInd;
    }

    /**
     * Sets the value of the cardPresentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardPresentInd(String value) {
        this.cardPresentInd = value;
    }

}
