//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salesResponse33 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesResponse33">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/sales}salesResponse32">
 *       &lt;sequence>
 *         &lt;element name="divisionNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="originalStoreDivisionNumber" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salesResponse33", namespace = "http://axes.alldata.net/web-services/sales", propOrder = {
    "divisionNumber",
    "originalStoreDivisionNumber"
})
@XmlSeeAlso({
    SalesResponse34 .class
})
public class SalesResponse33
    extends SalesResponse32
{

    protected Integer divisionNumber;
    protected Integer originalStoreDivisionNumber;

    /**
     * Gets the value of the divisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDivisionNumber() {
        return divisionNumber;
    }

    /**
     * Sets the value of the divisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDivisionNumber(Integer value) {
        this.divisionNumber = value;
    }

    /**
     * Gets the value of the originalStoreDivisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOriginalStoreDivisionNumber() {
        return originalStoreDivisionNumber;
    }

    /**
     * Sets the value of the originalStoreDivisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOriginalStoreDivisionNumber(Integer value) {
        this.originalStoreDivisionNumber = value;
    }

}
