//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salesResponse35 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesResponse35">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/sales}salesResponse34">
 *       &lt;sequence>
 *         &lt;element name="merchantDiscountFee" type="{http://axes.alldata.net/web-services/sales}merchantDiscountFee" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salesResponse35", namespace = "http://axes.alldata.net/web-services/sales", propOrder = {
    "merchantDiscountFee"
})
@XmlSeeAlso({
    SalesResponse36 .class
})
public class SalesResponse35
    extends SalesResponse34
{

    protected MerchantDiscountFee merchantDiscountFee;

    /**
     * Gets the value of the merchantDiscountFee property.
     * 
     * @return
     *     possible object is
     *     {@link MerchantDiscountFee }
     *     
     */
    public MerchantDiscountFee getMerchantDiscountFee() {
        return merchantDiscountFee;
    }

    /**
     * Sets the value of the merchantDiscountFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link MerchantDiscountFee }
     *     
     */
    public void setMerchantDiscountFee(MerchantDiscountFee value) {
        this.merchantDiscountFee = value;
    }

}
