//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salesResponse36 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesResponse36">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/sales}salesResponse35">
 *       &lt;sequence>
 *         &lt;element name="currentLoyaltyRewards" type="{http://axes.alldata.net/web-services/sales}currentRewards10" minOccurs="0"/>
 *         &lt;element name="nextLoyaltyRewards" type="{http://axes.alldata.net/web-services/sales}nextRewards" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salesResponse36", namespace = "http://axes.alldata.net/web-services/sales", propOrder = {
    "currentLoyaltyRewards",
    "nextLoyaltyRewards"
})
@XmlSeeAlso({
    SalesResponse37 .class
})
public class SalesResponse36
    extends SalesResponse35
{

    protected CurrentRewards10 currentLoyaltyRewards;
    protected NextRewards nextLoyaltyRewards;

    /**
     * Gets the value of the currentLoyaltyRewards property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentRewards10 }
     *     
     */
    public CurrentRewards10 getCurrentLoyaltyRewards() {
        return currentLoyaltyRewards;
    }

    /**
     * Sets the value of the currentLoyaltyRewards property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentRewards10 }
     *     
     */
    public void setCurrentLoyaltyRewards(CurrentRewards10 value) {
        this.currentLoyaltyRewards = value;
    }

    /**
     * Gets the value of the nextLoyaltyRewards property.
     * 
     * @return
     *     possible object is
     *     {@link NextRewards }
     *     
     */
    public NextRewards getNextLoyaltyRewards() {
        return nextLoyaltyRewards;
    }

    /**
     * Sets the value of the nextLoyaltyRewards property.
     * 
     * @param value
     *     allowed object is
     *     {@link NextRewards }
     *     
     */
    public void setNextLoyaltyRewards(NextRewards value) {
        this.nextLoyaltyRewards = value;
    }

}
