//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salesRequest35 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesRequest35">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/sales}salesRequest34">
 *       &lt;sequence>
 *         &lt;element name="clerkNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salesRequest35", namespace = "http://axes.alldata.net/web-services/sales", propOrder = {
    "clerkNumber"
})
@XmlSeeAlso({
    SalesRequest36 .class
})
public class SalesRequest35
    extends SalesRequest34
{

    protected String clerkNumber;

    /**
     * Gets the value of the clerkNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClerkNumber() {
        return clerkNumber;
    }

    /**
     * Sets the value of the clerkNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClerkNumber(String value) {
        this.clerkNumber = value;
    }

}
