//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "Sale3x", targetNamespace = "http://axes.alldata.net/web-services/sales")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Sale3X {


    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales33Response
     */
    @WebMethod
    @WebResult(name = "sales33Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales33Response sales33(
        @WebParam(name = "sales33", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales33 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales34Response
     */
    @WebMethod
    @WebResult(name = "sales34Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales34Response sales34(
        @WebParam(name = "sales34", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales34 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales35Response
     */
    @WebMethod
    @WebResult(name = "sales35Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales35Response sales35(
        @WebParam(name = "sales35", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales35 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales36Response
     */
    @WebMethod
    @WebResult(name = "sales36Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales36Response sales36(
        @WebParam(name = "sales36", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales36 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales30Response
     */
    @WebMethod
    @WebResult(name = "sales30Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales30Response sales30(
        @WebParam(name = "sales30", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales30 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales32Response
     */
    @WebMethod
    @WebResult(name = "sales32Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales32Response sales32(
        @WebParam(name = "sales32", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales32 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales37Response
     */
    @WebMethod
    @WebResult(name = "sales37Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales37Response sales37(
        @WebParam(name = "sales37", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales37 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.sales.Sales31Response
     */
    @WebMethod
    @WebResult(name = "sales31Response", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "result")
    public Sales31Response sales31(
        @WebParam(name = "sales31", targetNamespace = "http://axes.alldata.net/web-services/sales", partName = "parameters")
        Sales31 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/sales", header = true, partName = "Credentials")
        Credentials credentials);

}
