//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.sales;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for salesResponse34 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="salesResponse34">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/sales}salesResponse33">
 *       &lt;sequence>
 *         &lt;element name="estimatedPaymentData" type="{http://axes.alldata.net/web-services/sales}estimatedPaymentData" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "salesResponse34", namespace = "http://axes.alldata.net/web-services/sales", propOrder = {
    "estimatedPaymentData"
})
@XmlSeeAlso({
    SalesResponse35 .class
})
public class SalesResponse34
    extends SalesResponse33
{

    protected EstimatedPaymentData estimatedPaymentData;

    /**
     * Gets the value of the estimatedPaymentData property.
     * 
     * @return
     *     possible object is
     *     {@link EstimatedPaymentData }
     *     
     */
    public EstimatedPaymentData getEstimatedPaymentData() {
        return estimatedPaymentData;
    }

    /**
     * Sets the value of the estimatedPaymentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EstimatedPaymentData }
     *     
     */
    public void setEstimatedPaymentData(EstimatedPaymentData value) {
        this.estimatedPaymentData = value;
    }

}
