//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.ping;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.alldata.axes.web_services.ping package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Ping30_QNAME = new QName("http://axes.alldata.net/web-services/ping", "ping30");
    private final static QName _Credentials_QNAME = new QName("http://axes.alldata.net/web-services/ping", "credentials");
    private final static QName _Ping30Response_QNAME = new QName("http://axes.alldata.net/web-services/ping", "ping30Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.alldata.axes.web_services.ping
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PingRequest30 }
     * 
     */
    public PingRequest30 createPingRequest30() {
        return new PingRequest30();
    }

    /**
     * Create an instance of {@link Ping30 }
     * 
     */
    public Ping30 createPing30() {
        return new Ping30();
    }

    /**
     * Create an instance of {@link Ping30Response }
     * 
     */
    public Ping30Response createPing30Response() {
        return new Ping30Response();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link ClientHeader }
     * 
     */
    public ClientHeader createClientHeader() {
        return new ClientHeader();
    }

    /**
     * Create an instance of {@link Credentials }
     * 
     */
    public Credentials createCredentials() {
        return new Credentials();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ping30 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/ping", name = "ping30")
    public JAXBElement<Ping30> createPing30(Ping30 value) {
        return new JAXBElement<Ping30>(_Ping30_QNAME, Ping30 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Credentials }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/ping", name = "credentials")
    public JAXBElement<Credentials> createCredentials(Credentials value) {
        return new JAXBElement<Credentials>(_Credentials_QNAME, Credentials.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Ping30Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/ping", name = "ping30Response")
    public JAXBElement<Ping30Response> createPing30Response(Ping30Response value) {
        return new JAXBElement<Ping30Response>(_Ping30Response_QNAME, Ping30Response.class, null, value);
    }

}
