//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

// Dephin's comment

package net.alldata.axes.web_services.ping;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "Ping3x", targetNamespace = "http://axes.alldata.net/web-services/ping")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Ping3X {


    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.ping.Ping30Response
     */
    @WebMethod
    @WebResult(name = "ping30Response", targetNamespace = "http://axes.alldata.net/web-services/ping", partName = "result")
    public Ping30Response ping30(
        @WebParam(name = "ping30", targetNamespace = "http://axes.alldata.net/web-services/ping", partName = "parameters")
        Ping30 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/ping", header = true, partName = "Credentials")
        Credentials credentials);

}
