//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for authenticationQuestions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="authenticationQuestions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="sessionid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="applicationId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="question1" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *         &lt;element name="question2" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *         &lt;element name="question3" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *         &lt;element name="question4" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *         &lt;element name="question5" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *         &lt;element name="question6" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *         &lt;element name="question7" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *         &lt;element name="question8" type="{http://axes.alldata.net/web-services/instantCredit}authenticationQuestion" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "authenticationQuestions", namespace = "http://axes.alldata.net/web-services/instantCredit", propOrder = {
    "address",
    "sessionid",
    "applicationId",
    "type",
    "question1",
    "question2",
    "question3",
    "question4",
    "question5",
    "question6",
    "question7",
    "question8"
})
public class AuthenticationQuestions {

    protected Long address;
    protected String sessionid;
    protected String applicationId;
    protected String type;
    protected AuthenticationQuestion question1;
    protected AuthenticationQuestion question2;
    protected AuthenticationQuestion question3;
    protected AuthenticationQuestion question4;
    protected AuthenticationQuestion question5;
    protected AuthenticationQuestion question6;
    protected AuthenticationQuestion question7;
    protected AuthenticationQuestion question8;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAddress(Long value) {
        this.address = value;
    }

    /**
     * Gets the value of the sessionid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionid() {
        return sessionid;
    }

    /**
     * Sets the value of the sessionid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionid(String value) {
        this.sessionid = value;
    }

    /**
     * Gets the value of the applicationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicationId() {
        return applicationId;
    }

    /**
     * Sets the value of the applicationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicationId(String value) {
        this.applicationId = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the question1 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion1() {
        return question1;
    }

    /**
     * Sets the value of the question1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion1(AuthenticationQuestion value) {
        this.question1 = value;
    }

    /**
     * Gets the value of the question2 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion2() {
        return question2;
    }

    /**
     * Sets the value of the question2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion2(AuthenticationQuestion value) {
        this.question2 = value;
    }

    /**
     * Gets the value of the question3 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion3() {
        return question3;
    }

    /**
     * Sets the value of the question3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion3(AuthenticationQuestion value) {
        this.question3 = value;
    }

    /**
     * Gets the value of the question4 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion4() {
        return question4;
    }

    /**
     * Sets the value of the question4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion4(AuthenticationQuestion value) {
        this.question4 = value;
    }

    /**
     * Gets the value of the question5 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion5() {
        return question5;
    }

    /**
     * Sets the value of the question5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion5(AuthenticationQuestion value) {
        this.question5 = value;
    }

    /**
     * Gets the value of the question6 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion6() {
        return question6;
    }

    /**
     * Sets the value of the question6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion6(AuthenticationQuestion value) {
        this.question6 = value;
    }

    /**
     * Gets the value of the question7 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion7() {
        return question7;
    }

    /**
     * Sets the value of the question7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion7(AuthenticationQuestion value) {
        this.question7 = value;
    }

    /**
     * Gets the value of the question8 property.
     * 
     * @return
     *     possible object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public AuthenticationQuestion getQuestion8() {
        return question8;
    }

    /**
     * Sets the value of the question8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthenticationQuestion }
     *     
     */
    public void setQuestion8(AuthenticationQuestion value) {
        this.question8 = value;
    }

}
