//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bilingualRejectReasons complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bilingualRejectReasons">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bilingualLanguageInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bilingualRejectReason" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bilingualRejectReasons", namespace = "http://axes.alldata.net/web-services/instantCredit", propOrder = {
    "bilingualLanguageInd",
    "bilingualRejectReason"
})
public class BilingualRejectReasons {

    protected String bilingualLanguageInd;
    @XmlElement(nillable = true)
    protected List<String> bilingualRejectReason;

    /**
     * Gets the value of the bilingualLanguageInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBilingualLanguageInd() {
        return bilingualLanguageInd;
    }

    /**
     * Sets the value of the bilingualLanguageInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBilingualLanguageInd(String value) {
        this.bilingualLanguageInd = value;
    }

    /**
     * Gets the value of the bilingualRejectReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bilingualRejectReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBilingualRejectReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBilingualRejectReason() {
        if (bilingualRejectReason == null) {
            bilingualRejectReason = new ArrayList<String>();
        }
        return this.bilingualRejectReason;
    }

}
