//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for instantCredit35 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instantCredit35">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/instantCredit}instantCredit34">
 *       &lt;sequence>
 *         &lt;element name="customerMemberId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="rejectReason" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="bureauScore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="virtualCard" type="{http://axes.alldata.net/web-services/instantCredit}virtualCard" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instantCredit35", namespace = "http://axes.alldata.net/web-services/instantCredit", propOrder = {
    "customerMemberId",
    "rejectReason",
    "bureauScore",
    "virtualCard"
})
@XmlSeeAlso({
    InstantCredit36 .class
})
public class InstantCredit35
    extends InstantCredit34
{

    protected String customerMemberId;
    @XmlElement(nillable = true)
    protected List<String> rejectReason;
    protected Integer bureauScore;
    protected VirtualCard virtualCard;

    /**
     * Gets the value of the customerMemberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerMemberId() {
        return customerMemberId;
    }

    /**
     * Sets the value of the customerMemberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerMemberId(String value) {
        this.customerMemberId = value;
    }

    /**
     * Gets the value of the rejectReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rejectReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRejectReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRejectReason() {
        if (rejectReason == null) {
            rejectReason = new ArrayList<String>();
        }
        return this.rejectReason;
    }

    /**
     * Gets the value of the bureauScore property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBureauScore() {
        return bureauScore;
    }

    /**
     * Sets the value of the bureauScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBureauScore(Integer value) {
        this.bureauScore = value;
    }

    /**
     * Gets the value of the virtualCard property.
     * 
     * @return
     *     possible object is
     *     {@link VirtualCard }
     *     
     */
    public VirtualCard getVirtualCard() {
        return virtualCard;
    }

    /**
     * Sets the value of the virtualCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link VirtualCard }
     *     
     */
    public void setVirtualCard(VirtualCard value) {
        this.virtualCard = value;
    }

}
