//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for instantCreditRequest44 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instantCreditRequest44">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/instantCredit}instantCreditRequest43">
 *       &lt;sequence>
 *         &lt;element name="clientVariable1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientVariable2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientVariable3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientVariable4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="logo" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="referralCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instantCreditRequest44", namespace = "http://axes.alldata.net/web-services/instantCredit", propOrder = {
    "clientVariable1",
    "clientVariable2",
    "clientVariable3",
    "clientVariable4",
    "logo",
    "referralCode"
})
@XmlSeeAlso({
    InstantCreditRequest45 .class
})
public class InstantCreditRequest44
    extends InstantCreditRequest43
{

    protected String clientVariable1;
    protected String clientVariable2;
    protected String clientVariable3;
    protected String clientVariable4;
    protected Integer logo;
    protected String referralCode;

    /**
     * Gets the value of the clientVariable1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientVariable1() {
        return clientVariable1;
    }

    /**
     * Sets the value of the clientVariable1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientVariable1(String value) {
        this.clientVariable1 = value;
    }

    /**
     * Gets the value of the clientVariable2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientVariable2() {
        return clientVariable2;
    }

    /**
     * Sets the value of the clientVariable2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientVariable2(String value) {
        this.clientVariable2 = value;
    }

    /**
     * Gets the value of the clientVariable3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientVariable3() {
        return clientVariable3;
    }

    /**
     * Sets the value of the clientVariable3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientVariable3(String value) {
        this.clientVariable3 = value;
    }

    /**
     * Gets the value of the clientVariable4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientVariable4() {
        return clientVariable4;
    }

    /**
     * Sets the value of the clientVariable4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientVariable4(String value) {
        this.clientVariable4 = value;
    }

    /**
     * Gets the value of the logo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLogo() {
        return logo;
    }

    /**
     * Sets the value of the logo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLogo(Integer value) {
        this.logo = value;
    }

    /**
     * Gets the value of the referralCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferralCode() {
        return referralCode;
    }

    /**
     * Sets the value of the referralCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferralCode(String value) {
        this.referralCode = value;
    }

}
