//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "InstantCredit4x", targetNamespace = "http://axes.alldata.net/web-services/instantCredit")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InstantCredit4X {


    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit44Response
     */
    @WebMethod
    @WebResult(name = "instantCredit44Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit44Response instantCredit44(
        @WebParam(name = "instantCredit44", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit44 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit43Response
     */
    @WebMethod
    @WebResult(name = "instantCredit43Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit43Response instantCredit43(
        @WebParam(name = "instantCredit43", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit43 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit46Response
     */
    @WebMethod
    @WebResult(name = "instantCredit46Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit46Response instantCredit46(
        @WebParam(name = "instantCredit46", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit46 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit47Response
     */
    @WebMethod
    @WebResult(name = "instantCredit47Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit47Response instantCredit47(
        @WebParam(name = "instantCredit47", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit47 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit48Response
     */
    @WebMethod
    @WebResult(name = "instantCredit48Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit48Response instantCredit48(
        @WebParam(name = "instantCredit48", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit48 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit49Response
     */
    @WebMethod
    @WebResult(name = "instantCredit49Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit49Response instantCredit49(
        @WebParam(name = "instantCredit49", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit49 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit41Response
     */
    @WebMethod
    @WebResult(name = "instantCredit41Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit41Response instantCredit41(
        @WebParam(name = "instantCredit41", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit41 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit411Response
     */
    @WebMethod
    @WebResult(name = "instantCredit411Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit411Response instantCredit411(
        @WebParam(name = "instantCredit411", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit411 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit40Response
     */
    @WebMethod
    @WebResult(name = "instantCredit40Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit40Response instantCredit40(
        @WebParam(name = "instantCredit40", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit40 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit42Response
     */
    @WebMethod
    @WebResult(name = "instantCredit42Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit42Response instantCredit42(
        @WebParam(name = "instantCredit42", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit42 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit410Response
     */
    @WebMethod
    @WebResult(name = "instantCredit410Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit410Response instantCredit410(
        @WebParam(name = "instantCredit410", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit410 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services.instantcredit.InstantCredit45Response
     */
    @WebMethod
    @WebResult(name = "instantCredit45Response", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "result")
    public InstantCredit45Response instantCredit45(
        @WebParam(name = "instantCredit45", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", partName = "parameters")
        InstantCredit45 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", header = true, partName = "Credentials")
        Credentials credentials);

}
