//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for instantCredit34 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instantCredit34">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/instantCredit}instantCredit33">
 *       &lt;sequence>
 *         &lt;element name="creditTermType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instantCredit34", namespace = "http://axes.alldata.net/web-services/instantCredit", propOrder = {
    "creditTermType"
})
@XmlSeeAlso({
    InstantCredit35 .class
})
public class InstantCredit34
    extends InstantCredit33
{

    protected String creditTermType;

    /**
     * Gets the value of the creditTermType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditTermType() {
        return creditTermType;
    }

    /**
     * Sets the value of the creditTermType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditTermType(String value) {
        this.creditTermType = value;
    }

}
