//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "instantCredit4x", targetNamespace = "http://axes.alldata.net/web-services/instantCredit", wsdlLocation = "META-INF/wsdl/instantCredit4x.wsdl")
public class InstantCredit4X_Service
    extends Service
{

    private final static URL INSTANTCREDIT4X_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.alldata.axes.web_services.instantcredit.InstantCredit4X_Service.class.getName());

    static {
        URL url = null;
        try {
            url = net.alldata.axes.web_services.instantcredit.InstantCredit4X_Service.class.getResource("/META-INF/wsdl/instantCredit4x.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/instantCredit4x.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdl/instantCredit4x.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INSTANTCREDIT4X_WSDL_LOCATION = url;
    }

    public InstantCredit4X_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InstantCredit4X_Service() {
        super(INSTANTCREDIT4X_WSDL_LOCATION, new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit4x"));
    }

    /**
     * 
     * @return
     *     returns InstantCredit4X
     */
    @WebEndpoint(name = "InstantCredit4xPort")
    public InstantCredit4X getInstantCredit4XPort() {
        return super.getPort(new QName("http://axes.alldata.net/web-services/instantCredit", "InstantCredit4xPort"), InstantCredit4X.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InstantCredit4X
     */
    @WebEndpoint(name = "InstantCredit4xPort")
    public InstantCredit4X getInstantCredit4XPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://axes.alldata.net/web-services/instantCredit", "InstantCredit4xPort"), InstantCredit4X.class, features);
    }

}
