//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.alldata.axes.web_services.instantcredit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InstantCredit49Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit49Response");
    private final static QName _InstantCredit48_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit48");
    private final static QName _InstantCredit49_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit49");
    private final static QName _Credentials_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "credentials");
    private final static QName _InstantCredit46_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit46");
    private final static QName _InstantCredit47_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit47");
    private final static QName _InstantCredit410Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit410Response");
    private final static QName _InstantCredit44_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit44");
    private final static QName _InstantCredit411Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit411Response");
    private final static QName _InstantCredit45_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit45");
    private final static QName _InstantCredit42_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit42");
    private final static QName _InstantCredit43_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit43");
    private final static QName _InstantCredit40_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit40");
    private final static QName _InstantCredit41_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit41");
    private final static QName _AccountSummary40_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "accountSummary40");
    private final static QName _InstantCredit47Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit47Response");
    private final static QName _InstantCredit48Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit48Response");
    private final static QName _AccountSummary36_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "accountSummary36");
    private final static QName _InstantCredit45Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit45Response");
    private final static QName _InstantCredit46Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit46Response");
    private final static QName _InstantCredit43Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit43Response");
    private final static QName _InstantCredit411_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit411");
    private final static QName _InstantCredit44Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit44Response");
    private final static QName _InstantCredit41Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit41Response");
    private final static QName _InstantCredit410_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit410");
    private final static QName _InstantCredit42Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit42Response");
    private final static QName _InstantCredit40Response_QNAME = new QName("http://axes.alldata.net/web-services/instantCredit", "instantCredit40Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.alldata.axes.web_services.instantcredit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PrescreenAcceptance30 }
     * 
     */
    public PrescreenAcceptance30 createPrescreenAcceptance30() {
        return new PrescreenAcceptance30();
    }

    /**
     * Create an instance of {@link InstantCredit410Response }
     * 
     */
    public InstantCredit410Response createInstantCredit410Response() {
        return new InstantCredit410Response();
    }

    /**
     * Create an instance of {@link InstantCredit41Response }
     * 
     */
    public InstantCredit41Response createInstantCredit41Response() {
        return new InstantCredit41Response();
    }

    /**
     * Create an instance of {@link InstantCreditRequest40 }
     * 
     */
    public InstantCreditRequest40 createInstantCreditRequest40() {
        return new InstantCreditRequest40();
    }

    /**
     * Create an instance of {@link PrescreenAcceptance36 }
     * 
     */
    public PrescreenAcceptance36 createPrescreenAcceptance36() {
        return new PrescreenAcceptance36();
    }

    /**
     * Create an instance of {@link InstantCredit40Response }
     * 
     */
    public InstantCredit40Response createInstantCredit40Response() {
        return new InstantCredit40Response();
    }

    /**
     * Create an instance of {@link CurrentRewards }
     * 
     */
    public CurrentRewards createCurrentRewards() {
        return new CurrentRewards();
    }

    /**
     * Create an instance of {@link InstantCredit34 }
     * 
     */
    public InstantCredit34 createInstantCredit34() {
        return new InstantCredit34();
    }

    /**
     * Create an instance of {@link Iovation }
     * 
     */
    public Iovation createIovation() {
        return new Iovation();
    }

    /**
     * Create an instance of {@link InstantCredit43 }
     * 
     */
    public InstantCredit43 createInstantCredit43() {
        return new InstantCredit43();
    }

    /**
     * Create an instance of {@link InstantCreditResponse46 }
     * 
     */
    public InstantCreditResponse46 createInstantCreditResponse46() {
        return new InstantCreditResponse46();
    }

    /**
     * Create an instance of {@link JointApplicant }
     * 
     */
    public JointApplicant createJointApplicant() {
        return new JointApplicant();
    }

    /**
     * Create an instance of {@link VirtualCard }
     * 
     */
    public VirtualCard createVirtualCard() {
        return new VirtualCard();
    }

    /**
     * Create an instance of {@link InstantCreditResponse40 }
     * 
     */
    public InstantCreditResponse40 createInstantCreditResponse40() {
        return new InstantCreditResponse40();
    }

    /**
     * Create an instance of {@link InstantCreditResponse42 }
     * 
     */
    public InstantCreditResponse42 createInstantCreditResponse42() {
        return new InstantCreditResponse42();
    }

    /**
     * Create an instance of {@link InstantCreditRequest47 }
     * 
     */
    public InstantCreditRequest47 createInstantCreditRequest47() {
        return new InstantCreditRequest47();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link InstantCredit47 }
     * 
     */
    public InstantCredit47 createInstantCredit47() {
        return new InstantCredit47();
    }

    /**
     * Create an instance of {@link InstantCredit47Response }
     * 
     */
    public InstantCredit47Response createInstantCredit47Response() {
        return new InstantCredit47Response();
    }

    /**
     * Create an instance of {@link NextRewards }
     * 
     */
    public NextRewards createNextRewards() {
        return new NextRewards();
    }

    /**
     * Create an instance of {@link InstantCreditRequest411 }
     * 
     */
    public InstantCreditRequest411 createInstantCreditRequest411() {
        return new InstantCreditRequest411();
    }

    /**
     * Create an instance of {@link InstantCreditResponse49 }
     * 
     */
    public InstantCreditResponse49 createInstantCreditResponse49() {
        return new InstantCreditResponse49();
    }

    /**
     * Create an instance of {@link InstantCreditRequest43 }
     * 
     */
    public InstantCreditRequest43 createInstantCreditRequest43() {
        return new InstantCreditRequest43();
    }

    /**
     * Create an instance of {@link InstantCredit38 }
     * 
     */
    public InstantCredit38 createInstantCredit38() {
        return new InstantCredit38();
    }

    /**
     * Create an instance of {@link InstantCredit42 }
     * 
     */
    public InstantCredit42 createInstantCredit42() {
        return new InstantCredit42();
    }

    /**
     * Create an instance of {@link InstantCredit46Response }
     * 
     */
    public InstantCredit46Response createInstantCredit46Response() {
        return new InstantCredit46Response();
    }

    /**
     * Create an instance of {@link InstantCredit48Response }
     * 
     */
    public InstantCredit48Response createInstantCredit48Response() {
        return new InstantCredit48Response();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link InstantCreditResponse44 }
     * 
     */
    public InstantCreditResponse44 createInstantCreditResponse44() {
        return new InstantCreditResponse44();
    }

    /**
     * Create an instance of {@link InstantCredit46 }
     * 
     */
    public InstantCredit46 createInstantCredit46() {
        return new InstantCredit46();
    }

    /**
     * Create an instance of {@link AccountSummary36 }
     * 
     */
    public AccountSummary36 createAccountSummary36() {
        return new AccountSummary36();
    }

    /**
     * Create an instance of {@link PrescreenAcceptance37 }
     * 
     */
    public PrescreenAcceptance37 createPrescreenAcceptance37() {
        return new PrescreenAcceptance37();
    }

    /**
     * Create an instance of {@link InstantCreditRequest45 }
     * 
     */
    public InstantCreditRequest45 createInstantCreditRequest45() {
        return new InstantCreditRequest45();
    }

    /**
     * Create an instance of {@link InstantCredit49 }
     * 
     */
    public InstantCredit49 createInstantCredit49() {
        return new InstantCredit49();
    }

    /**
     * Create an instance of {@link InstantCredit35 }
     * 
     */
    public InstantCredit35 createInstantCredit35() {
        return new InstantCredit35();
    }

    /**
     * Create an instance of {@link ClientHeader }
     * 
     */
    public ClientHeader createClientHeader() {
        return new ClientHeader();
    }

    /**
     * Create an instance of {@link PrescreenAcceptance34 }
     * 
     */
    public PrescreenAcceptance34 createPrescreenAcceptance34() {
        return new PrescreenAcceptance34();
    }

    /**
     * Create an instance of {@link InstantCreditResponse47 }
     * 
     */
    public InstantCreditResponse47 createInstantCreditResponse47() {
        return new InstantCreditResponse47();
    }

    /**
     * Create an instance of {@link CurrentRewards10 }
     * 
     */
    public CurrentRewards10 createCurrentRewards10() {
        return new CurrentRewards10();
    }

    /**
     * Create an instance of {@link InstantCredit41 }
     * 
     */
    public InstantCredit41 createInstantCredit41() {
        return new InstantCredit41();
    }

    /**
     * Create an instance of {@link InstantCredit43Response }
     * 
     */
    public InstantCredit43Response createInstantCredit43Response() {
        return new InstantCredit43Response();
    }

    /**
     * Create an instance of {@link InstantCreditResponse41 }
     * 
     */
    public InstantCreditResponse41 createInstantCreditResponse41() {
        return new InstantCreditResponse41();
    }

    /**
     * Create an instance of {@link InstantCredit32 }
     * 
     */
    public InstantCredit32 createInstantCredit32() {
        return new InstantCredit32();
    }

    /**
     * Create an instance of {@link InstantCredit39 }
     * 
     */
    public InstantCredit39 createInstantCredit39() {
        return new InstantCredit39();
    }

    /**
     * Create an instance of {@link InstantCreditResponse411 }
     * 
     */
    public InstantCreditResponse411 createInstantCreditResponse411() {
        return new InstantCreditResponse411();
    }

    /**
     * Create an instance of {@link Credentials }
     * 
     */
    public Credentials createCredentials() {
        return new Credentials();
    }

    /**
     * Create an instance of {@link InstantCredit411 }
     * 
     */
    public InstantCredit411 createInstantCredit411() {
        return new InstantCredit411();
    }

    /**
     * Create an instance of {@link InstantCredit45Response }
     * 
     */
    public InstantCredit45Response createInstantCredit45Response() {
        return new InstantCredit45Response();
    }

    /**
     * Create an instance of {@link SecondSource10 }
     * 
     */
    public SecondSource10 createSecondSource10() {
        return new SecondSource10();
    }

    /**
     * Create an instance of {@link InstantCredit48 }
     * 
     */
    public InstantCredit48 createInstantCredit48() {
        return new InstantCredit48();
    }

    /**
     * Create an instance of {@link InstantCreditRequest41 }
     * 
     */
    public InstantCreditRequest41 createInstantCreditRequest41() {
        return new InstantCreditRequest41();
    }

    /**
     * Create an instance of {@link InstantCreditRequest44 }
     * 
     */
    public InstantCreditRequest44 createInstantCreditRequest44() {
        return new InstantCreditRequest44();
    }

    /**
     * Create an instance of {@link AuthenticationQuestions10 }
     * 
     */
    public AuthenticationQuestions10 createAuthenticationQuestions10() {
        return new AuthenticationQuestions10();
    }

    /**
     * Create an instance of {@link PersonalizeCard10 }
     * 
     */
    public PersonalizeCard10 createPersonalizeCard10() {
        return new PersonalizeCard10();
    }

    /**
     * Create an instance of {@link InstantCredit44Response }
     * 
     */
    public InstantCredit44Response createInstantCredit44Response() {
        return new InstantCredit44Response();
    }

    /**
     * Create an instance of {@link AuthenticationQuestion }
     * 
     */
    public AuthenticationQuestion createAuthenticationQuestion() {
        return new AuthenticationQuestion();
    }

    /**
     * Create an instance of {@link InstantCredit40 }
     * 
     */
    public InstantCredit40 createInstantCredit40() {
        return new InstantCredit40();
    }

    /**
     * Create an instance of {@link InstantCredit36 }
     * 
     */
    public InstantCredit36 createInstantCredit36() {
        return new InstantCredit36();
    }

    /**
     * Create an instance of {@link PrescreenAcceptance38 }
     * 
     */
    public PrescreenAcceptance38 createPrescreenAcceptance38() {
        return new PrescreenAcceptance38();
    }

    /**
     * Create an instance of {@link InstantCreditResponse45 }
     * 
     */
    public InstantCreditResponse45 createInstantCreditResponse45() {
        return new InstantCreditResponse45();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link PrescreenAcceptance35 }
     * 
     */
    public PrescreenAcceptance35 createPrescreenAcceptance35() {
        return new PrescreenAcceptance35();
    }

    /**
     * Create an instance of {@link InstantCredit411Response }
     * 
     */
    public InstantCredit411Response createInstantCredit411Response() {
        return new InstantCredit411Response();
    }

    /**
     * Create an instance of {@link InstantCredit410 }
     * 
     */
    public InstantCredit410 createInstantCredit410() {
        return new InstantCredit410();
    }

    /**
     * Create an instance of {@link InstantCreditRequest46 }
     * 
     */
    public InstantCreditRequest46 createInstantCreditRequest46() {
        return new InstantCreditRequest46();
    }

    /**
     * Create an instance of {@link InstantCredit49Response }
     * 
     */
    public InstantCredit49Response createInstantCredit49Response() {
        return new InstantCredit49Response();
    }

    /**
     * Create an instance of {@link SecondSource11 }
     * 
     */
    public SecondSource11 createSecondSource11() {
        return new SecondSource11();
    }

    /**
     * Create an instance of {@link InstantCredit33 }
     * 
     */
    public InstantCredit33 createInstantCredit33() {
        return new InstantCredit33();
    }

    /**
     * Create an instance of {@link BilingualRejectReasons }
     * 
     */
    public BilingualRejectReasons createBilingualRejectReasons() {
        return new BilingualRejectReasons();
    }

    /**
     * Create an instance of {@link InstantCreditResponse48 }
     * 
     */
    public InstantCreditResponse48 createInstantCreditResponse48() {
        return new InstantCreditResponse48();
    }

    /**
     * Create an instance of {@link InstantCreditRequest48 }
     * 
     */
    public InstantCreditRequest48 createInstantCreditRequest48() {
        return new InstantCreditRequest48();
    }

    /**
     * Create an instance of {@link InstantCredit44 }
     * 
     */
    public InstantCredit44 createInstantCredit44() {
        return new InstantCredit44();
    }

    /**
     * Create an instance of {@link InstantCreditRequest410 }
     * 
     */
    public InstantCreditRequest410 createInstantCreditRequest410() {
        return new InstantCreditRequest410();
    }

    /**
     * Create an instance of {@link InstantCreditResponse410 }
     * 
     */
    public InstantCreditResponse410 createInstantCreditResponse410() {
        return new InstantCreditResponse410();
    }

    /**
     * Create an instance of {@link InstantCredit45 }
     * 
     */
    public InstantCredit45 createInstantCredit45() {
        return new InstantCredit45();
    }

    /**
     * Create an instance of {@link AccountSummary40 }
     * 
     */
    public AccountSummary40 createAccountSummary40() {
        return new AccountSummary40();
    }

    /**
     * Create an instance of {@link AuthBuyer }
     * 
     */
    public AuthBuyer createAuthBuyer() {
        return new AuthBuyer();
    }

    /**
     * Create an instance of {@link InstantCredit37 }
     * 
     */
    public InstantCredit37 createInstantCredit37() {
        return new InstantCredit37();
    }

    /**
     * Create an instance of {@link InstantCreditRequest42 }
     * 
     */
    public InstantCreditRequest42 createInstantCreditRequest42() {
        return new InstantCreditRequest42();
    }

    /**
     * Create an instance of {@link InstantCredit30 }
     * 
     */
    public InstantCredit30 createInstantCredit30() {
        return new InstantCredit30();
    }

    /**
     * Create an instance of {@link AuthenticationQuestions }
     * 
     */
    public AuthenticationQuestions createAuthenticationQuestions() {
        return new AuthenticationQuestions();
    }

    /**
     * Create an instance of {@link InstantCreditResponse43 }
     * 
     */
    public InstantCreditResponse43 createInstantCreditResponse43() {
        return new InstantCreditResponse43();
    }

    /**
     * Create an instance of {@link InstantCreditRequest49 }
     * 
     */
    public InstantCreditRequest49 createInstantCreditRequest49() {
        return new InstantCreditRequest49();
    }

    /**
     * Create an instance of {@link InstantCredit42Response }
     * 
     */
    public InstantCredit42Response createInstantCredit42Response() {
        return new InstantCredit42Response();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit49Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit49Response")
    public JAXBElement<InstantCredit49Response> createInstantCredit49Response(InstantCredit49Response value) {
        return new JAXBElement<InstantCredit49Response>(_InstantCredit49Response_QNAME, InstantCredit49Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit48 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit48")
    public JAXBElement<InstantCredit48> createInstantCredit48(InstantCredit48 value) {
        return new JAXBElement<InstantCredit48>(_InstantCredit48_QNAME, InstantCredit48 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit49 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit49")
    public JAXBElement<InstantCredit49> createInstantCredit49(InstantCredit49 value) {
        return new JAXBElement<InstantCredit49>(_InstantCredit49_QNAME, InstantCredit49 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Credentials }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "credentials")
    public JAXBElement<Credentials> createCredentials(Credentials value) {
        return new JAXBElement<Credentials>(_Credentials_QNAME, Credentials.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit46 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit46")
    public JAXBElement<InstantCredit46> createInstantCredit46(InstantCredit46 value) {
        return new JAXBElement<InstantCredit46>(_InstantCredit46_QNAME, InstantCredit46 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit47 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit47")
    public JAXBElement<InstantCredit47> createInstantCredit47(InstantCredit47 value) {
        return new JAXBElement<InstantCredit47>(_InstantCredit47_QNAME, InstantCredit47 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit410Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit410Response")
    public JAXBElement<InstantCredit410Response> createInstantCredit410Response(InstantCredit410Response value) {
        return new JAXBElement<InstantCredit410Response>(_InstantCredit410Response_QNAME, InstantCredit410Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit44 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit44")
    public JAXBElement<InstantCredit44> createInstantCredit44(InstantCredit44 value) {
        return new JAXBElement<InstantCredit44>(_InstantCredit44_QNAME, InstantCredit44 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit411Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit411Response")
    public JAXBElement<InstantCredit411Response> createInstantCredit411Response(InstantCredit411Response value) {
        return new JAXBElement<InstantCredit411Response>(_InstantCredit411Response_QNAME, InstantCredit411Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit45 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit45")
    public JAXBElement<InstantCredit45> createInstantCredit45(InstantCredit45 value) {
        return new JAXBElement<InstantCredit45>(_InstantCredit45_QNAME, InstantCredit45 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit42 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit42")
    public JAXBElement<InstantCredit42> createInstantCredit42(InstantCredit42 value) {
        return new JAXBElement<InstantCredit42>(_InstantCredit42_QNAME, InstantCredit42 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit43 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit43")
    public JAXBElement<InstantCredit43> createInstantCredit43(InstantCredit43 value) {
        return new JAXBElement<InstantCredit43>(_InstantCredit43_QNAME, InstantCredit43 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit40 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit40")
    public JAXBElement<InstantCredit40> createInstantCredit40(InstantCredit40 value) {
        return new JAXBElement<InstantCredit40>(_InstantCredit40_QNAME, InstantCredit40 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit41 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit41")
    public JAXBElement<InstantCredit41> createInstantCredit41(InstantCredit41 value) {
        return new JAXBElement<InstantCredit41>(_InstantCredit41_QNAME, InstantCredit41 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountSummary40 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "accountSummary40")
    public JAXBElement<AccountSummary40> createAccountSummary40(AccountSummary40 value) {
        return new JAXBElement<AccountSummary40>(_AccountSummary40_QNAME, AccountSummary40 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit47Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit47Response")
    public JAXBElement<InstantCredit47Response> createInstantCredit47Response(InstantCredit47Response value) {
        return new JAXBElement<InstantCredit47Response>(_InstantCredit47Response_QNAME, InstantCredit47Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit48Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit48Response")
    public JAXBElement<InstantCredit48Response> createInstantCredit48Response(InstantCredit48Response value) {
        return new JAXBElement<InstantCredit48Response>(_InstantCredit48Response_QNAME, InstantCredit48Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccountSummary36 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "accountSummary36")
    public JAXBElement<AccountSummary36> createAccountSummary36(AccountSummary36 value) {
        return new JAXBElement<AccountSummary36>(_AccountSummary36_QNAME, AccountSummary36 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit45Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit45Response")
    public JAXBElement<InstantCredit45Response> createInstantCredit45Response(InstantCredit45Response value) {
        return new JAXBElement<InstantCredit45Response>(_InstantCredit45Response_QNAME, InstantCredit45Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit46Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit46Response")
    public JAXBElement<InstantCredit46Response> createInstantCredit46Response(InstantCredit46Response value) {
        return new JAXBElement<InstantCredit46Response>(_InstantCredit46Response_QNAME, InstantCredit46Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit43Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit43Response")
    public JAXBElement<InstantCredit43Response> createInstantCredit43Response(InstantCredit43Response value) {
        return new JAXBElement<InstantCredit43Response>(_InstantCredit43Response_QNAME, InstantCredit43Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit411 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit411")
    public JAXBElement<InstantCredit411> createInstantCredit411(InstantCredit411 value) {
        return new JAXBElement<InstantCredit411>(_InstantCredit411_QNAME, InstantCredit411 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit44Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit44Response")
    public JAXBElement<InstantCredit44Response> createInstantCredit44Response(InstantCredit44Response value) {
        return new JAXBElement<InstantCredit44Response>(_InstantCredit44Response_QNAME, InstantCredit44Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit41Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit41Response")
    public JAXBElement<InstantCredit41Response> createInstantCredit41Response(InstantCredit41Response value) {
        return new JAXBElement<InstantCredit41Response>(_InstantCredit41Response_QNAME, InstantCredit41Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit410 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit410")
    public JAXBElement<InstantCredit410> createInstantCredit410(InstantCredit410 value) {
        return new JAXBElement<InstantCredit410>(_InstantCredit410_QNAME, InstantCredit410 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit42Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit42Response")
    public JAXBElement<InstantCredit42Response> createInstantCredit42Response(InstantCredit42Response value) {
        return new JAXBElement<InstantCredit42Response>(_InstantCredit42Response_QNAME, InstantCredit42Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstantCredit40Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/instantCredit", name = "instantCredit40Response")
    public JAXBElement<InstantCredit40Response> createInstantCredit40Response(InstantCredit40Response value) {
        return new JAXBElement<InstantCredit40Response>(_InstantCredit40Response_QNAME, InstantCredit40Response.class, null, value);
    }

}
