//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for prescreenAcceptance37 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prescreenAcceptance37">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/instantCredit}prescreenAcceptance36">
 *       &lt;sequence>
 *         &lt;element name="bilingualRejectReasons" type="{http://axes.alldata.net/web-services/instantCredit}bilingualRejectReasons" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prescreenAcceptance37", namespace = "http://axes.alldata.net/web-services/instantCredit", propOrder = {
    "bilingualRejectReasons"
})
@XmlSeeAlso({
    PrescreenAcceptance38 .class
})
public class PrescreenAcceptance37
    extends PrescreenAcceptance36
{

    protected BilingualRejectReasons bilingualRejectReasons;

    /**
     * Gets the value of the bilingualRejectReasons property.
     * 
     * @return
     *     possible object is
     *     {@link BilingualRejectReasons }
     *     
     */
    public BilingualRejectReasons getBilingualRejectReasons() {
        return bilingualRejectReasons;
    }

    /**
     * Sets the value of the bilingualRejectReasons property.
     * 
     * @param value
     *     allowed object is
     *     {@link BilingualRejectReasons }
     *     
     */
    public void setBilingualRejectReasons(BilingualRejectReasons value) {
        this.bilingualRejectReasons = value;
    }

}
