//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services.instantcredit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for prescreenAcceptance36 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="prescreenAcceptance36">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/instantCredit}prescreenAcceptance35">
 *       &lt;sequence>
 *         &lt;element name="personalizeCard" type="{http://axes.alldata.net/web-services/instantCredit}personalizeCard10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "prescreenAcceptance36", namespace = "http://axes.alldata.net/web-services/instantCredit", propOrder = {
    "personalizeCard"
})
@XmlSeeAlso({
    PrescreenAcceptance37 .class
})
public class PrescreenAcceptance36
    extends PrescreenAcceptance35
{

    protected PersonalizeCard10 personalizeCard;

    /**
     * Gets the value of the personalizeCard property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalizeCard10 }
     *     
     */
    public PersonalizeCard10 getPersonalizeCard() {
        return personalizeCard;
    }

    /**
     * Sets the value of the personalizeCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalizeCard10 }
     *     
     */
    public void setPersonalizeCard(PersonalizeCard10 value) {
        this.personalizeCard = value;
    }

}
