//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services._void;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.alldata.axes.web_services._void package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sale36_QNAME = new QName("http://axes.alldata.net/web-services/void", "sale36");
    private final static QName _Sale37_QNAME = new QName("http://axes.alldata.net/web-services/void", "sale37");
    private final static QName _Void30_QNAME = new QName("http://axes.alldata.net/web-services/void", "void30");
    private final static QName _Return34Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "return34Response");
    private final static QName _Void31_QNAME = new QName("http://axes.alldata.net/web-services/void", "void31");
    private final static QName _Void32_QNAME = new QName("http://axes.alldata.net/web-services/void", "void32");
    private final static QName _Return35Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "return35Response");
    private final static QName _Return36Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "return36Response");
    private final static QName _Void33_QNAME = new QName("http://axes.alldata.net/web-services/void", "void33");
    private final static QName _Return37Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "return37Response");
    private final static QName _Void34_QNAME = new QName("http://axes.alldata.net/web-services/void", "void34");
    private final static QName _Void35_QNAME = new QName("http://axes.alldata.net/web-services/void", "void35");
    private final static QName _Credentials_QNAME = new QName("http://axes.alldata.net/web-services/void", "credentials");
    private final static QName _Sale36Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "sale36Response");
    private final static QName _Sale37Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "sale37Response");
    private final static QName _Return34_QNAME = new QName("http://axes.alldata.net/web-services/void", "return34");
    private final static QName _Return35_QNAME = new QName("http://axes.alldata.net/web-services/void", "return35");
    private final static QName _Void30Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "void30Response");
    private final static QName _Return36_QNAME = new QName("http://axes.alldata.net/web-services/void", "return36");
    private final static QName _Void31Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "void31Response");
    private final static QName _Return37_QNAME = new QName("http://axes.alldata.net/web-services/void", "return37");
    private final static QName _Void32Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "void32Response");
    private final static QName _Void33Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "void33Response");
    private final static QName _Void34Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "void34Response");
    private final static QName _Void35Response_QNAME = new QName("http://axes.alldata.net/web-services/void", "void35Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.alldata.axes.web_services._void
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Sale37Response }
     * 
     */
    public Sale37Response createSale37Response() {
        return new Sale37Response();
    }

    /**
     * Create an instance of {@link Credentials }
     * 
     */
    public Credentials createCredentials() {
        return new Credentials();
    }

    /**
     * Create an instance of {@link Return36 }
     * 
     */
    public Return36 createReturn36() {
        return new Return36();
    }

    /**
     * Create an instance of {@link Void31 }
     * 
     */
    public Void31 createVoid31() {
        return new Void31();
    }

    /**
     * Create an instance of {@link VoidResponse35 }
     * 
     */
    public VoidResponse35 createVoidResponse35() {
        return new VoidResponse35();
    }

    /**
     * Create an instance of {@link Sale37 }
     * 
     */
    public Sale37 createSale37() {
        return new Sale37();
    }

    /**
     * Create an instance of {@link VoidRequest34 }
     * 
     */
    public VoidRequest34 createVoidRequest34() {
        return new VoidRequest34();
    }

    /**
     * Create an instance of {@link VoidResponse32 }
     * 
     */
    public VoidResponse32 createVoidResponse32() {
        return new VoidResponse32();
    }

    /**
     * Create an instance of {@link VoidRequest36 }
     * 
     */
    public VoidRequest36 createVoidRequest36() {
        return new VoidRequest36();
    }

    /**
     * Create an instance of {@link Void33 }
     * 
     */
    public Void33 createVoid33() {
        return new Void33();
    }

    /**
     * Create an instance of {@link Return37Response }
     * 
     */
    public Return37Response createReturn37Response() {
        return new Return37Response();
    }

    /**
     * Create an instance of {@link VoidResponse37 }
     * 
     */
    public VoidResponse37 createVoidResponse37() {
        return new VoidResponse37();
    }

    /**
     * Create an instance of {@link Void31Response }
     * 
     */
    public Void31Response createVoid31Response() {
        return new Void31Response();
    }

    /**
     * Create an instance of {@link CurrentRewards10 }
     * 
     */
    public CurrentRewards10 createCurrentRewards10() {
        return new CurrentRewards10();
    }

    /**
     * Create an instance of {@link Void34Response }
     * 
     */
    public Void34Response createVoid34Response() {
        return new Void34Response();
    }

    /**
     * Create an instance of {@link Return34 }
     * 
     */
    public Return34 createReturn34() {
        return new Return34();
    }

    /**
     * Create an instance of {@link Void32 }
     * 
     */
    public Void32 createVoid32() {
        return new Void32();
    }

    /**
     * Create an instance of {@link Sale36 }
     * 
     */
    public Sale36 createSale36() {
        return new Sale36();
    }

    /**
     * Create an instance of {@link Void32Response }
     * 
     */
    public Void32Response createVoid32Response() {
        return new Void32Response();
    }

    /**
     * Create an instance of {@link VoidResponse31 }
     * 
     */
    public VoidResponse31 createVoidResponse31() {
        return new VoidResponse31();
    }

    /**
     * Create an instance of {@link ClientHeader }
     * 
     */
    public ClientHeader createClientHeader() {
        return new ClientHeader();
    }

    /**
     * Create an instance of {@link VoidResponse34 }
     * 
     */
    public VoidResponse34 createVoidResponse34() {
        return new VoidResponse34();
    }

    /**
     * Create an instance of {@link VoidResponse30 }
     * 
     */
    public VoidResponse30 createVoidResponse30() {
        return new VoidResponse30();
    }

    /**
     * Create an instance of {@link Void30 }
     * 
     */
    public Void30 createVoid30() {
        return new Void30();
    }

    /**
     * Create an instance of {@link VoidRequest31 }
     * 
     */
    public VoidRequest31 createVoidRequest31() {
        return new VoidRequest31();
    }

    /**
     * Create an instance of {@link NextRewards }
     * 
     */
    public NextRewards createNextRewards() {
        return new NextRewards();
    }

    /**
     * Create an instance of {@link VoidRequest33 }
     * 
     */
    public VoidRequest33 createVoidRequest33() {
        return new VoidRequest33();
    }

    /**
     * Create an instance of {@link Void34 }
     * 
     */
    public Void34 createVoid34() {
        return new Void34();
    }

    /**
     * Create an instance of {@link Sale36Response }
     * 
     */
    public Sale36Response createSale36Response() {
        return new Sale36Response();
    }

    /**
     * Create an instance of {@link Void30Response }
     * 
     */
    public Void30Response createVoid30Response() {
        return new Void30Response();
    }

    /**
     * Create an instance of {@link Return37 }
     * 
     */
    public Return37 createReturn37() {
        return new Return37();
    }

    /**
     * Create an instance of {@link Return35Response }
     * 
     */
    public Return35Response createReturn35Response() {
        return new Return35Response();
    }

    /**
     * Create an instance of {@link VoidRequest35 }
     * 
     */
    public VoidRequest35 createVoidRequest35() {
        return new VoidRequest35();
    }

    /**
     * Create an instance of {@link VoidResponse33 }
     * 
     */
    public VoidResponse33 createVoidResponse33() {
        return new VoidResponse33();
    }

    /**
     * Create an instance of {@link VoidResponse36 }
     * 
     */
    public VoidResponse36 createVoidResponse36() {
        return new VoidResponse36();
    }

    /**
     * Create an instance of {@link Return34Response }
     * 
     */
    public Return34Response createReturn34Response() {
        return new Return34Response();
    }

    /**
     * Create an instance of {@link VoidRequest37 }
     * 
     */
    public VoidRequest37 createVoidRequest37() {
        return new VoidRequest37();
    }

    /**
     * Create an instance of {@link Void35 }
     * 
     */
    public Void35 createVoid35() {
        return new Void35();
    }

    /**
     * Create an instance of {@link CurrentRewards }
     * 
     */
    public CurrentRewards createCurrentRewards() {
        return new CurrentRewards();
    }

    /**
     * Create an instance of {@link VoidRequest30 }
     * 
     */
    public VoidRequest30 createVoidRequest30() {
        return new VoidRequest30();
    }

    /**
     * Create an instance of {@link Return35 }
     * 
     */
    public Return35 createReturn35() {
        return new Return35();
    }

    /**
     * Create an instance of {@link Void35Response }
     * 
     */
    public Void35Response createVoid35Response() {
        return new Void35Response();
    }

    /**
     * Create an instance of {@link Void33Response }
     * 
     */
    public Void33Response createVoid33Response() {
        return new Void33Response();
    }

    /**
     * Create an instance of {@link VoidRequest32 }
     * 
     */
    public VoidRequest32 createVoidRequest32() {
        return new VoidRequest32();
    }

    /**
     * Create an instance of {@link Return36Response }
     * 
     */
    public Return36Response createReturn36Response() {
        return new Return36Response();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sale36 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "sale36")
    public JAXBElement<Sale36> createSale36(Sale36 value) {
        return new JAXBElement<Sale36>(_Sale36_QNAME, Sale36 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sale37 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "sale37")
    public JAXBElement<Sale37> createSale37(Sale37 value) {
        return new JAXBElement<Sale37>(_Sale37_QNAME, Sale37 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void30 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void30")
    public JAXBElement<Void30> createVoid30(Void30 value) {
        return new JAXBElement<Void30>(_Void30_QNAME, Void30 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return34Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return34Response")
    public JAXBElement<Return34Response> createReturn34Response(Return34Response value) {
        return new JAXBElement<Return34Response>(_Return34Response_QNAME, Return34Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void31 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void31")
    public JAXBElement<Void31> createVoid31(Void31 value) {
        return new JAXBElement<Void31>(_Void31_QNAME, Void31 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void32 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void32")
    public JAXBElement<Void32> createVoid32(Void32 value) {
        return new JAXBElement<Void32>(_Void32_QNAME, Void32 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return35Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return35Response")
    public JAXBElement<Return35Response> createReturn35Response(Return35Response value) {
        return new JAXBElement<Return35Response>(_Return35Response_QNAME, Return35Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return36Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return36Response")
    public JAXBElement<Return36Response> createReturn36Response(Return36Response value) {
        return new JAXBElement<Return36Response>(_Return36Response_QNAME, Return36Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void33 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void33")
    public JAXBElement<Void33> createVoid33(Void33 value) {
        return new JAXBElement<Void33>(_Void33_QNAME, Void33 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return37Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return37Response")
    public JAXBElement<Return37Response> createReturn37Response(Return37Response value) {
        return new JAXBElement<Return37Response>(_Return37Response_QNAME, Return37Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void34 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void34")
    public JAXBElement<Void34> createVoid34(Void34 value) {
        return new JAXBElement<Void34>(_Void34_QNAME, Void34 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void35 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void35")
    public JAXBElement<Void35> createVoid35(Void35 value) {
        return new JAXBElement<Void35>(_Void35_QNAME, Void35 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Credentials }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "credentials")
    public JAXBElement<Credentials> createCredentials(Credentials value) {
        return new JAXBElement<Credentials>(_Credentials_QNAME, Credentials.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sale36Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "sale36Response")
    public JAXBElement<Sale36Response> createSale36Response(Sale36Response value) {
        return new JAXBElement<Sale36Response>(_Sale36Response_QNAME, Sale36Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Sale37Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "sale37Response")
    public JAXBElement<Sale37Response> createSale37Response(Sale37Response value) {
        return new JAXBElement<Sale37Response>(_Sale37Response_QNAME, Sale37Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return34 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return34")
    public JAXBElement<Return34> createReturn34(Return34 value) {
        return new JAXBElement<Return34>(_Return34_QNAME, Return34 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return35 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return35")
    public JAXBElement<Return35> createReturn35(Return35 value) {
        return new JAXBElement<Return35>(_Return35_QNAME, Return35 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void30Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void30Response")
    public JAXBElement<Void30Response> createVoid30Response(Void30Response value) {
        return new JAXBElement<Void30Response>(_Void30Response_QNAME, Void30Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return36 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return36")
    public JAXBElement<Return36> createReturn36(Return36 value) {
        return new JAXBElement<Return36>(_Return36_QNAME, Return36 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void31Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void31Response")
    public JAXBElement<Void31Response> createVoid31Response(Void31Response value) {
        return new JAXBElement<Void31Response>(_Void31Response_QNAME, Void31Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Return37 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "return37")
    public JAXBElement<Return37> createReturn37(Return37 value) {
        return new JAXBElement<Return37>(_Return37_QNAME, Return37 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void32Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void32Response")
    public JAXBElement<Void32Response> createVoid32Response(Void32Response value) {
        return new JAXBElement<Void32Response>(_Void32Response_QNAME, Void32Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void33Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void33Response")
    public JAXBElement<Void33Response> createVoid33Response(Void33Response value) {
        return new JAXBElement<Void33Response>(_Void33Response_QNAME, Void33Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void34Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void34Response")
    public JAXBElement<Void34Response> createVoid34Response(Void34Response value) {
        return new JAXBElement<Void34Response>(_Void34Response_QNAME, Void34Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Void35Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://axes.alldata.net/web-services/void", name = "void35Response")
    public JAXBElement<Void35Response> createVoid35Response(Void35Response value) {
        return new JAXBElement<Void35Response>(_Void35Response_QNAME, Void35Response.class, null, value);
    }

}
