//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services._void;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for voidRequest36 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="voidRequest36">
 *   &lt;complexContent>
 *     &lt;extension base="{http://axes.alldata.net/web-services/void}voidRequest35">
 *       &lt;sequence>
 *         &lt;element name="cardDataInputCapability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardHolderPresentInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cardPresentInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hostDataCaptureInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "voidRequest36", namespace = "http://axes.alldata.net/web-services/void", propOrder = {
    "cardDataInputCapability",
    "cardHolderPresentInd",
    "cardPresentInd",
    "hostDataCaptureInd"
})
@XmlSeeAlso({
    VoidRequest37 .class
})
public class VoidRequest36
    extends VoidRequest35
{

    protected String cardDataInputCapability;
    protected String cardHolderPresentInd;
    protected String cardPresentInd;
    protected String hostDataCaptureInd;

    /**
     * Gets the value of the cardDataInputCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardDataInputCapability() {
        return cardDataInputCapability;
    }

    /**
     * Sets the value of the cardDataInputCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardDataInputCapability(String value) {
        this.cardDataInputCapability = value;
    }

    /**
     * Gets the value of the cardHolderPresentInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardHolderPresentInd() {
        return cardHolderPresentInd;
    }

    /**
     * Sets the value of the cardHolderPresentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardHolderPresentInd(String value) {
        this.cardHolderPresentInd = value;
    }

    /**
     * Gets the value of the cardPresentInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardPresentInd() {
        return cardPresentInd;
    }

    /**
     * Sets the value of the cardPresentInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardPresentInd(String value) {
        this.cardPresentInd = value;
    }

    /**
     * Gets the value of the hostDataCaptureInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHostDataCaptureInd() {
        return hostDataCaptureInd;
    }

    /**
     * Sets the value of the hostDataCaptureInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHostDataCaptureInd(String value) {
        this.hostDataCaptureInd = value;
    }

}
