//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services._void;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "void3x", targetNamespace = "http://axes.alldata.net/web-services/void", wsdlLocation = "META-INF/wsdl/void3x.wsdl")
public class Void3X_Service
    extends Service
{

    private final static URL VOID3X_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(net.alldata.axes.web_services._void.Void3X_Service.class.getName());

    static {
        URL url = null;
        try {
            url = net.alldata.axes.web_services._void.Void3X_Service.class.getResource("/META-INF/wsdl/void3x.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/void3x.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdl/void3x.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VOID3X_WSDL_LOCATION = url;
    }

    public Void3X_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Void3X_Service() {
        super(VOID3X_WSDL_LOCATION, new QName("http://axes.alldata.net/web-services/void", "void3x"));
    }

    /**
     * 
     * @return
     *     returns Void3X
     */
    @WebEndpoint(name = "Void3xPort")
    public Void3X getVoid3XPort() {
        return super.getPort(new QName("http://axes.alldata.net/web-services/void", "Void3xPort"), Void3X.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Void3X
     */
    @WebEndpoint(name = "Void3xPort")
    public Void3X getVoid3XPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://axes.alldata.net/web-services/void", "Void3xPort"), Void3X.class, features);
    }

}
