//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package net.alldata.axes.web_services._void;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

@WebService(name = "Void3x", targetNamespace = "http://axes.alldata.net/web-services/void")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Void3X {


    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Sale36Response
     */
    @WebMethod
    @WebResult(name = "sale36Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Sale36Response sale36(
        @WebParam(name = "sale36", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Sale36 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Void33Response
     */
    @WebMethod
    @WebResult(name = "void33Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Void33Response void33(
        @WebParam(name = "void33", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Void33 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Return35Response
     */
    @WebMethod
    @WebResult(name = "return35Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Return35Response return35(
        @WebParam(name = "return35", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Return35 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Void30Response
     */
    @WebMethod
    @WebResult(name = "void30Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Void30Response void30(
        @WebParam(name = "void30", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Void30 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Sale37Response
     */
    @WebMethod
    @WebResult(name = "sale37Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Sale37Response sale37(
        @WebParam(name = "sale37", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Sale37 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Return37Response
     */
    @WebMethod
    @WebResult(name = "return37Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Return37Response return37(
        @WebParam(name = "return37", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Return37 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Void34Response
     */
    @WebMethod
    @WebResult(name = "void34Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Void34Response void34(
        @WebParam(name = "void34", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Void34 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Void35Response
     */
    @WebMethod
    @WebResult(name = "void35Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Void35Response void35(
        @WebParam(name = "void35", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Void35 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Return36Response
     */
    @WebMethod
    @WebResult(name = "return36Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Return36Response return36(
        @WebParam(name = "return36", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Return36 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Return34Response
     */
    @WebMethod
    @WebResult(name = "return34Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Return34Response return34(
        @WebParam(name = "return34", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Return34 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Void32Response
     */
    @WebMethod
    @WebResult(name = "void32Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Void32Response void32(
        @WebParam(name = "void32", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Void32 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

    /**
     * 
     * @param parameters
     * @param credentials
     * @return
     *     returns net.alldata.axes.web_services._void.Void31Response
     */
    @WebMethod
    @WebResult(name = "void31Response", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "result")
    public Void31Response void31(
        @WebParam(name = "void31", targetNamespace = "http://axes.alldata.net/web-services/void", partName = "parameters")
        Void31 parameters,
        @WebParam(name = "credentials", targetNamespace = "http://axes.alldata.net/web-services/void", header = true, partName = "Credentials")
        Credentials credentials);

}
